### ISSUE TITLE
It's seems tether.io doesn't contain lib's website anymore

### ISSUE THREAD

**Issue by Seminioni** [shipshapecode/tether#1066]
Where to read docs?

**Comment by rwwagner90** [comment]
Uh oh, we definitely need to get some docs up! 😬

**Comment by rwwagner90** [comment]
For now, you can view docs at http://shipshapecode.github.io/tether/ @Seminioni

**Comment by Seminioni** [comment]
Thanks man. Great job

**Comment by rwwagner90** [comment]
Just moved to https://tetherjs.dev/ for anyone who ends up here
