### ISSUE TITLE
Native Tether in CSS? Maybe!

### ISSUE THREAD

**Issue by soluml** [shipshapecode/tether#107]
Hey Guys!

Wanted to reach out to you, hopefully this is a good way to do so.  Over on the [Web Platform Incubator Community Group discourse site](http://discourse.wicg.io/t/position-an-element-relatively-to-another-element-from-anywhere-in-the-dom/968/23), the idea of doing essentially what Tether does natively has "popped up" (pun intended).  Would really value your guys' input and experience if you guys have anything to add to the discussion!

**Comment by adamschwartz** [comment]
:100: This would truly change the lives of frontenders everywhere. (A more substantial comment to come...)
