### ISSUE TITLE
Scroll down arrows don't work on Tether demo page

### ISSUE THREAD

**Issue by dandv** [shipshapecode/tether#108]
1. Go to http://tether.io/#usage
2. Click on the scroll down arrow
3. Nothing happens. The other three scroll arrows work, and dragging the scrollbar thumb behaves as expected. Clicking in the scrollbar works too.

Can reproduce in Chrome 44 and Firefox 39.

![scroll down arrows don t work](https://cloud.githubusercontent.com/assets/33569/8930914/0615ac80-34e7-11e5-858e-5dab1271cfbd.gif)

**Comment by TrevorBurnham** [comment]
@dandv Is this still the case? I'm having a hard time replicating because I'm on a Mac.

**Comment by dandv** [comment]
Yep, the issue is still there in Chrome 52.0.2713.0 canary (64-bit) on Windows. The bottom right scrollbar arrow just isn't clickable.

**Comment by TrevorBurnham** [comment]
Is there an element in front of it? Try right-clicking there and choosing "Inspect".

**Comment by dandv** [comment]
No element that's not over other parts of the two scrollbars.

![image](https://cloud.githubusercontent.com/assets/33569/14724949/0e78e2b0-07ce-11e6-9c2b-051143e85cac.png)

**Comment by rwwagner90** [comment]
This is a minor issue, so not planning to fix it at this time.
