### ISSUE TITLE
Official React version of the library?

### ISSUE THREAD

**Issue by oyeanuj** [shipshapecode/tether#144]
Hi folks! Tether looks great but it seems on researching that there are different attempts to make tether work well with React but all fragile. 

I was curious if there were any plans to do any official React version of this library?

**Comment by geekjuice** [comment]
\cc @banderson @colbyr

**Comment by souporserious** [comment]
I'm maintaining this and open to any suggestions on how to improve it https://github.com/souporserious/react-tether

**Comment by yairEO** [comment]
why would you need a React wrapper? you can just include Tether in your build process (gulp, grunt..) and be done with it. what benefits would a React wrapper would give?

I think ES6 exports would be a better thing to support.

**Comment by silvenon** [comment]
@yairEO not having to pass refs around and trying to find the exact point in time and space when you're allowed to initialize Tether. The build process is not a problem.

@souporserious :heart:

**Comment by AndrewIngram** [comment]
@yairEO last time I checked tether updates the DOM itself, whereas a more React-friendly API would emit reposition events rather than doing the repositioning itself.

**Comment by slorber** [comment]
Used tether directly myself before but built something complex with react-tether and it works great thanks @souporserious

**Comment by rwwagner90** [comment]
It looks like @danreeves keeps things pretty updated for react-tether. @danreeves would you be open to trying out some of the new betas as we release them and clean things up?

**Comment by danreeves** [comment]
of course. PRs also welcome!
