### ISSUE TITLE
Option to disable `position: fixed`

### ISSUE THREAD

**Issue by krasnoukhov** [shipshapecode/tether#152]
Tether is a great library and it works great for most of the cases. However, consider following case:
- Page size is small enough so there is no scroll
- Element is big enough so it does not fit into that page
- In my case, attachment is as follows: `tether-element-attached-middle tether-element-attached-right tether-target-attached-middle tether-target-attached-left`

Given that preconditions, Tether applies `position: fixed` to the element, which basically prevents browser from growing page size and user couldn't scroll to the bottom of the element. Please note that this is not a case when it's attached to opposite sides.

I tried commenting out case in `move` function that sets fixed position and it worked well. So I'm wondering maybe that can be something that could be disabled through `optimizations` hash?

Please let me know what you think, I'd be happy to provide a PR.

**Comment by xandrani** [comment]
I'm really passed off now.

I've unsubscribed twice yet I still get these emails. When are ShitHub
going to fix this.

They obviously do zero testing. This is utter bullshit.

**Comment by krasnoukhov** [comment]
@xandrani Not sure how this is related to the issue, but I'm sorry that is happening to you

**Comment by geekjuice** [comment]
@xandrani A possible solution could be sign onto the web app (maybe the mobile version as well) and unwatch the project. I'm sorry you are still getting these emails, but for the future, please bring this up to GitHub support. As I mentioned previously, this is not problem is not related this project and shouldn't be brought into here.

**Comment by krasnoukhov** [comment]
Any update on this? Thanks

**Comment by zackbloom** [comment]
It could certainly be disabled here: https://github.com/HubSpot/tether/blob/master/src/js/tether.js#L726

Feel free to make a PR.

**Comment by rwwagner90** [comment]
This landed here https://github.com/shipshapecode/tether/pull/308
