### ISSUE TITLE
No way of using it with Bootstrap 4 in angular2 app (angular-cli)

### ISSUE THREAD

**Issue by alvipeo** [shipshapecode/tether#177]
Angular cli projects use system.js and if you try to use Bootstrap 4 (which requires tether) you're in trouble.
1. you can't use 'import "tether"' - this just doesn't work. Bootstrap throws
2. I tried to use it with "script" tag - this makes ng2 app work but tests fail

See my angular cli issues:
- https://github.com/angular/angular-cli/issues/630
- https://github.com/angular/angular-cli/issues/699

**Comment by alvipeo** [comment]
Related issues - https://github.com/angular/angular-cli/issues/630
and this one - https://github.com/angular/angular-cli/issues/699

**Comment by jrosseel** [comment]
Ran into the same problem today. Fixed it by removing the bootstrap dependency through npm. Then added Bootstrap v4.0.0-alpha.3
