### ISSUE TITLE
UglifyJS warnings

### ISSUE THREAD

**Issue by ayozebarrera** [shipshapecode/tether#183]
Hi, there are some warnings on your code:

```
Condition always true [./~/tether/dist/js/tether.js:4,0]
Dropping unreachable code [./~/tether/dist/js/tether.js:6,3]
Dropping side-effect-free statement [./~/tether/dist/js/tether.js:378,0]
Dropping side-effect-free statement [./~/tether/dist/js/tether.js:1225,0]
Dropping side-effect-free statement [./~/tether/dist/js/tether.js:1601,0]
Dropping side-effect-free statement [./~/tether/dist/js/tether.js:1675,0]
```

**Comment by DiscoNova** [comment]
I would say that is probably a "false positive" ... the condition "always" evaluates to true if/when uglify is executes in AMD-context and ... apparently it then proceeds to *drop* the parts of the code that is *meant* to handle the exact situation where the library was not included in an AMD-context. Way to go Uglify!

I might be wrong though, wouldn't be the first time.

However - here is something to take home: "so-called 'unreachable code' might not be unreachable if it ever gets executed in another context" ;)

**Comment by DiscoNova** [comment]
Blaah... actually, let's consider that this might *not* be a false positive. Please provide the setup you are executing uglify under.

And if you feel like it, please open an issue on @ mishoo/UglifyJS ... it might be tether's problem ... but it is more like that it is theirs ... we might as well give it a shotgun-treatment ... shoot everything that moves :D

**Comment by ayozebarrera** [comment]
shotgun-treatment nice hehe

I'm using webpack command --optimize that uses UglifyJS. Can't tell much more... just check your code and it its ok ignore me :D I did this just for help

see ya

**Comment by rwwagner90** [comment]
I believe this should be fixed now.
