### ISSUE TITLE
Tether not compiled correctly

### ISSUE THREAD

**Issue by ibedek** [shipshapecode/tether#187]
It has multiple definitions for same function (eg. extend function in dist/js/tether.js or same function in minified version) and that causes problems when using ASP.net bundles - browser throws an exception.
Issue noticed when using bootstrap 4 tooltip, but could be on almost every plugin that depends on Tether.

**Comment by MichaelRando** [comment]
Yes. My bug is the same: https://github.com/rollup/rollup/issues/1289

**Comment by mbaierl** [comment]
Since the original request has been on June 30 already - are there going to be any updates to this library?

**Comment by Echooff3** [comment]
I had a similar issue when using ASP.net bundling. In my case, it was affecting _setOptions_. From what I could tell it minified getScrollParents as 'r' and internal to the function minified the line here [tether.js line 666](https://github.com/HubSpot/tether/blob/master/dist/js/tether.js#L666) to 'r' as well.

My quick fix was to modify the function slightly to play nice with the rest of the code. 
I commented out line 666 and replace [line 731](https://github.com/HubSpot/tether/blob/master/dist/js/tether.js#L731) with the following:
```
this.enable(arguments.length <= 1 || arguments[1] === undefined ? true : arguments[1]);
```
This freed up the redefinition of 'r' and allowed it to remain minified as getScrollParents

**Comment by rwwagner90** [comment]
This is fixed now. Please try the latest 2.x version!
