### ISSUE TITLE
Feature request: nudgeX and nudgeY parameters

### ISSUE THREAD

**Issue by stewhouston** [shipshapecode/tether#194]
I'm sure there are quite a few perfectionists who use this library, and sometimes the generated position of the tooltip/drop isn't quite flush with a desired layout element.

I've written a wrapper for both classes that allow 'nudgeX' and 'nudgeY' parameters to be specified when instantiating a tooltip/drop. Before the tether element is displayed to the user, the CSS values for the transform (translateX and translateY) are updated to take into account the nudge values, which can be positive or negative.

It would be fantastic if this was a native feature of the library.

**Comment by FezVrasta** [comment]
What's wrong with the `offset` option?

**Comment by rwwagner90** [comment]
I agree with @FezVrasta, this is supported via `offset`.
