### ISSUE TITLE
SVGAnimatedString is not defined

### ISSUE THREAD

**Issue by rubenbp** [shipshapecode/tether#201]
Hi!

In some navigators, when a new Tether class is instantiated the following error occurs:

SVGAnimatedString is not defined
in this [line of code](https://github.com/HubSpot/tether/blob/master/src/js/utils.js#L251).

I could log errors that occur only on Android 2.3.x devices.

These are some of the user agent of the affected devices:

`User-Agent: Mozilla/5.0 (Linux; U; Android 2.3.6; es-es; GT-S6500D Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1`

`User-Agent: Mozilla/5.0 (Linux; U; Android 2.3.4; es-es; SonyEricssonMT15i Build/4.0.2.A.0.62) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1`

Thanks

**Comment by rwwagner90** [comment]
`SVGAnimatedString` is no longer used, so this should be fixed!
