### ISSUE TITLE
Tether CDN

### ISSUE THREAD

**Issue by danger89** [shipshapecode/tether#220]
So using tether via CDN is good, also explained here:
https://cdnjs.com/libraries/tether/1.3.7

You say in your README.md this:
`<script src="//cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js"></script>`

But, what about integrity & crossorigin? jQuery & Bootstrap has these elements filled in for security reasons. Hopefully you will do the same as well?

Thanks!
- Melroy

**Comment by pubkey** [comment]
@danger89 I created a [pull-request](https://github.com/HubSpot/tether/pull/237).
Please confirm that it does what you ment.

**Comment by danger89** [comment]
Sorry I didn't react.
