### ISSUE TITLE
Re-attaching tethered element when item is temporarily removed from DOM

### ISSUE THREAD

**Issue by tnrich** [shipshapecode/tether#222]
Hey there,

So in my use case, I am tethering to an item in an infinite list. As I scroll the infinite list, even before the item goes off the page, the item is removed from the dom and then re-inserted as the row above. 

I was wondering if there is a way to have tether still stay attached after this instantaneous reinsertion. 

Hopefully my issue makes sense..

Thanks!

**Comment by tnrich** [comment]
Here is a gif of the situation to help make things more clear: 

![asdfasdfasd](https://cloud.githubusercontent.com/assets/2730609/20366459/12c31d46-ac00-11e6-9fc1-49c02bef180d.gif)

**Comment by TrevorBurnham** [comment]
There's no way for Tether to detect that its target has been removed/re-added to the DOM. You may want to consider inserting a target element that you control yourself inside of the scroll container, positioning it wherever you want the Tether to be attached using `position: absolute`.

**Comment by tnrich** [comment]
Hmm thanks for the quick replay @TrevorBurnham 

Another thing I was thinking was that I could use some sort of "onUntether" event handler to recreate the connection, but I didn't see such an event described in the docs. Is there something that can do that?

Thanks!

**Comment by TrevorBurnham** [comment]
> Another thing I was thinking was that I could use some sort of `onUntether` event handler to recreate the connection

The trouble is that Tether doesn't really know when its target is removed from the DOM; there's no DOM event for that. Rather, the Tether disappears when it detects the `scroll` event and its target no longer exists. I don't think it would be intuitive for the Tether API to include an `onUntether` event that only fires under those specific circumstances.

**Comment by chuckcarpenter** [comment]
I believe in this instance you'd want to attach a new tether to the element when it comes back into view in the scroll parent.
