### ISSUE TITLE
attachment: 'top right' only has the right position after first onResize()

### ISSUE THREAD

**Issue by pubkey** [shipshapecode/tether#238]
I created a tether between 2 elements with the following js:

```js
new Tether({
  element: '#a1234',
  target: '#target',
  attachment: 'top right',
  targetAttachment: 'top left'
});
```

When the tether is created, the ```#a1234``` is located to far left of the ```#target```.
But the moment I resize the window, the position gets fixed.

[JS-Fiddle](https://jsfiddle.net/6x0p4m7y/3/) to reproduce.

Tested on Chrome and Firefox.

**Comment by TrevorBurnham** [comment]
That's very strange. I have no idea where that initial `transformX` value is coming from. 😕

**Comment by bgoerdt** [comment]
This is happening for me as well, only with a different combination of settings (attachment: 'bottom right', targetAttachment: 'bottom left'). I called position() on the tether object after I created it and it fixed the issue for now.

[JSFiddle](https://jsfiddle.net/bgoerdt/Ldooo0wm/)

**Comment by geotheory** [comment]
I've encountered the same problem. I have some code that resizes panels responsively, and I've found, strangely, that tether only works if I duplicate the code above _and_ below the responsive code.

**Comment by cleverplatypus** [comment]
This is still happening.

Trying to tether a menu with the settings

```js
new Tether({
    element: menuEl.value,
    target: selfEl.value,
    attachment: 'top right',
    targetAttachment: 'bottom right',
    offset: '-5px 0',
    constraints: [{
        to: 'body'
    }]
})
```

will render like this 
<img width="315" alt="image" src="https://github.com/shipshapecode/tether/assets/1626868/420f0894-fb8c-42cf-b51a-c5ea689bac9e">

Resizing the window seems to trigger positioning to the right, however the positioning is a bit haphazard.

<img width="295" alt="image" src="https://github.com/shipshapecode/tether/assets/1626868/28f07869-97b2-433b-90eb-7f52d0ada1e9">
