### ISSUE TITLE
no version information in min.js

### ISSUE THREAD

**Issue by gtz42** [shipshapecode/tether#239]
When tether is bundled in other projects, it's usually the minified/uglified version that is bundled.
Unfortunately this file does not contain any information about the version.
e.g. jQuery leaves this string:
`/*! jQuery v2.2.2 | (c) jQuery Foundation | jquery.org/license */`
Could you please keep such a string in tether, too?
Thanks.

Alternatively: is there a list of known tether.mini.js she-sums?

**Comment by yairEO** [comment]
I would like to also suggest adding the license comment to the distributed JS files
