### ISSUE TITLE
add instructions for how to build the examples

### ISSUE THREAD

**Issue by humanchimp** [shipshapecode/tether#242]
I saw that it is possible to view examples [http://tether.io/examples/list_of_examples/](on the tether.io website). It would be nice if there was a way to get them to work locally, so that they can be twiddled with. It seems like fixing this might just be a matter of adding documentation?

**Comment by rwwagner90** [comment]
@humanchimp the examples live in the `examples` directory. If you build the code and open the html files for the examples, they will run.
