### ISSUE TITLE
Problem using tether with webpack (Angular CLI)

### ISSUE THREAD

**Issue by wm1sr** [shipshapecode/tether#244]
I'm developing a project using Angular CLI.
So I installed tether using `npm install tether --save`, and imported the depedency in app.component.ts
using `import * as Tether from 'tether'`.

When I try to initialize Tether with `new Tether({ ... })` it gives me the following console output 
when that statement is executed: 

> EXCEPTION: __WEBPACK_IMPORTED_MODULE_4_tether__ is not a constructor

If I print the Tether variable using console.log(Tether) it gives me what it seems an empty object.

Could you guys help me? I've never used neither typescript nor webpack before, so I'm sorry if I'm missing something obvious here.

**Comment by Namek** [comment]
It's exactly how I use it and it works proerly for me.

**Comment by rwwagner90** [comment]
Without a reproduction of this error, and with the fact it works for @Namek, I am going to close. If you are still having issues, please let us know!
