### ISSUE TITLE
setting 2 targets (top/left)

### ISSUE THREAD

**Issue by yairEO** [shipshapecode/tether#246]
I'm in dire need to set a complex target, where the `top` (**y-axis**) of my tether element will be attached to `target-1` element, and the `left` or 'right' (**x-axis**) of the tether element will be attached to `target-2` element.

### I need this for complex tooltips positioning:

![aaa](https://cloud.githubusercontent.com/assets/845031/22863177/297396cc-f144-11e6-8cee-004d870e5b3e.png)

I need the checkbox tooltip to be aligned (on the x-axis) to the whole `fieldset` which holds the checkbox and the texts.  There are 3 fieldsets (same width ofc) and the tooltips are aligned to the x-axis. 

For the **y-axis**, I need the tooltips to be aligned to the input elements themselves. 
The height of each `fieldset` containing each input may vary (and they also have padding)...which then will not position the tooltips relative to the **y-axis** of the `input` elements themselves.

### The following cannot guarantee the results needed

    attachment       : 'middle left',
    targetAttachment : 'middle right'

-----------
Hope the situation is well understood

**Comment by FezVrasta** [comment]
You should create 3 divs that wrap the 3 sections and attach the tooltips to them.

**Comment by yairEO** [comment]
@FezVrasta - that is an ugly hack and is not an elegant solution. 
Such logic should be transparent and should not require the developer to make HTML & CSS modifications which might require a hell of a lot work to do. 

This work is intended for large-scale organization and doing HTML changes requires TONS of bureaucracy and isn't worth the time. Also, others might also need this feature, therefor doing it within Tether will benefit more, I believe.

**Comment by FezVrasta** [comment]
I don't see a clean solution implementable in the library,it would require a lot of custom logic. My approach is the cleanest
