### ISSUE TITLE
Can't disable classes

### ISSUE THREAD

**Issue by dimensi** [shipshapecode/tether#253]
Hi, I'm trying to disable classes that I do not need.
```js
new Tether({
                element: this.$el,
                target: this.target,
                attachment: 'top left',
                targetAttachment: 'bottom left',
                constraints: [
                    {
                        to: 'scrollParent',
                        attachment: 'together'
                    }
                ],
                classPrefix: 'popup',
                classes: {
                    element: false,
                    target: false,
                    enabled: false
                }
            });
```
But everything is useless, the classes are only renamed, but not switched off.

**Comment by shmax** [comment]
I was just about to report this, myself. The offending bit of code seems to be [here](https://github.com/HubSpot/tether/blob/3d7119e590661f8c9e9e566c8a7640c189687215/src/js/tether.js#L201). A truthy check is done on `classes[key]`, but if it's been set to false as suggested in the docs, then it simply falls down to the next check for `this.options.classPrefix`, and if that fails, it just returns the key. There is no path that results in no class being added. Or am I missing something?

**Comment by Cryrivers** [comment]
Had the same issue.
