### ISSUE TITLE
Tether not initialize window.Tether when loaded by ReqireJS

### ISSUE THREAD

**Issue by NTMan** [shipshapecode/tether#257]
It's headache to write shim for Tether for working bootstrap 4, because init in shim  launched after bootstrap loaded and it's impossible solve issue without crutch. On many sites offer solving issue by writing fake Tether module which would call original Tether and define window.Tether variable with right value. But I think this is not right way. For example for jquery not needed such squats.

```js
    shim: {
       "tether": {
            exports: "Tether"
        },
        "bootstrap" : {
            deps :['jquery', 'tether'],
            init: function (jquery, tether) {
                console.log(tether);
                window.Tether = tether;
            }
        }
    }
```

**Comment by rwwagner90** [comment]
All importing and shimming issues should be fixed with the new build. Please try the new betas and let us know if you are still experiencing issues!
