### ISSUE TITLE
Not Compatible with TypeScript compiler

### ISSUE THREAD

**Issue by mweiczorek** [shipshapecode/tether#263]
When compiling with Typescript compiler, I get these errors - same with the minified version.

Error:(52, 14) TS2300:Duplicate identifier 'getScrollParents'.
Error:(138, 14) TS2300:Duplicate identifier 'removeUtilElements'.
Error:(145, 14) TS2300:Duplicate identifier 'getBounds'.
Error:(178, 14) TS2300:Duplicate identifier 'getOffsetParent'.
Error:(183, 14) TS2300:Duplicate identifier 'getScrollBarSize'.
Error:(223, 14) TS2300:Duplicate identifier 'extend'.
Error:(243, 14) TS2300:Duplicate identifier 'removeClass'.
Error:(257, 14) TS2300:Duplicate identifier 'addClass'.
Error:(292, 14) TS2300:Duplicate identifier 'updateClasses'.
Error:(436, 9) TS2300:Duplicate identifier 'getScrollParents'.
Error:(437, 9) TS2300:Duplicate identifier 'getBounds'.
Error:(438, 9) TS2300:Duplicate identifier 'getOffsetParent'.
Error:(439, 9) TS2300:Duplicate identifier 'extend'.
Error:(440, 9) TS2300:Duplicate identifier 'addClass'.
Error:(441, 9) TS2300:Duplicate identifier 'removeClass'.
Error:(442, 9) TS2300:Duplicate identifier 'updateClasses'.
Error:(445, 9) TS2300:Duplicate identifier 'getScrollBarSize'.
Error:(446, 9) TS2300:Duplicate identifier 'removeUtilElements'.
Error:(1308, 9) TS2300:Duplicate identifier 'getBounds'.
Error:(1309, 9) TS2300:Duplicate identifier 'extend'.
Error:(1310, 9) TS2300:Duplicate identifier 'updateClasses'.
Error:(1694, 9) TS2300:Duplicate identifier 'getBounds'.
Error:(1695, 9) TS2300:Duplicate identifier 'updateClasses'.

**Comment by rwwagner90** [comment]
@mweiczorek I believe this should be fixed, now that we have moved away from gulp. If you are still experiencing issues, please let us know!
