### ISSUE TITLE
Constraits doesn't work with parent scroll based on CSS transform (like smooth-scrollbar)

### ISSUE THREAD

**Issue by Naararouter** [shipshapecode/tether#281]
Hey! I was very glad when I could find perfect custom scroll library for my project - https://github.com/idiotWu/smooth-scrollbar (It's good worked with replacing MacOS scroll + mobile devices). But what was my disappointment when I found out that Tether did not work with this properly. In particular, its constraits. Tell me, please, You are planning add this abillity to Tether? Maybe, Is it possible with Popper which you notice on main github page?
Thank you!

**Comment by rwwagner90** [comment]
That library says to not use it, as it does not allow for native look and feel. I don't think there is a reliable way to support all the different custom scroll libraries, so I am going to close this for now. If anyone has a good idea on how to support things like this, let us know!
