### ISSUE TITLE
Does not compile with parcel-bundler

### ISSUE THREAD

**Issue by pke** [shipshapecode/tether#284]
When using this library (through reactstrap) with parcel-bundler it throws this error:

`...\node_modules\reactstrap-tether\dist\js\tether.js:549:21: Cannot resolve dependency './utils' at '...\node_modules\reactstrap-tether\dist\js\utils'`

Seems like the generated dist package is incorrect.

**Comment by rwwagner90** [comment]
@pke I believe this should be fixed now. Could you try `2.0.0-beta.2`?

**Comment by pke** [comment]
Thanks for looking into this. I currently don't remember in which project I used tether but I'll try to reproduce.

**Comment by pke** [comment]
Seems to work, but could also been because of parcel itself being a new version than 1 1/2 year ago. I am going to close this.
