### ISSUE TITLE
No test cases to run the package

### ISSUE THREAD

**Issue by ShreyaGoel08** [shipshapecode/tether#293]
Hi,

I am trying to test the tether package, but every time I get no test specified as result.
```
root@ebd716dea412:/tether# npm install-test
audited 2931 packages in 14.837s
found 9 vulnerabilities (4 low, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> tether@1.4.5 test /tether
> mocha

Warning: Could not find any test files matching pattern: test
No test files found
npm ERR! Test failed.  See above for more details.
```
Steps to reproduce the behavior 
1- Git clone https://github.com/HubSpot/tether.
2- cd tether
3- npm install-test.

Can anyone tell me how to run the test in tether package

**Comment by rwwagner90** [comment]
Hi @ShreyaGoel08, I do not think there are any tests, but we will be writing some soon, as we work to modernize and revitalize tether!
