### ISSUE TITLE
Compiling issue: 5:29-36 Critical dependency

### ISSUE THREAD

**Issue by 13addata** [shipshapecode/tether#294]
I got this error massage in Chrome: 

`Error: Bootstrap tooltips require Tether (http://tether.io/) app.js line 4049 > eval:674:45`

`[WDS] Warnings while compiling. index.js:147`
`./src/assets/plugins/tether/dist/js/tether.js`
`15:29-36 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`
 `@ ./src/assets/plugins/tether/dist/js/tether.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js`

What I am trying to do it to is to convert a .html file (a static page) to a project with webpack(vue-cli)

`<script src="assets/plugins/jquery/dist/jquery.min.js"></script>`
`<script src="assets/plugins/tether/dist/js/tether.min.js"></script>`
`<script src="assets/plugins/bootstrap/dist/js/bootstrap.min.js"></script>`
`<script src="assets/plugins/slick-carousel/slick/slick.min.js"></script>`

So here I put these codes on the top of my main.js file:
`import './assets/plugins/jquery/dist/jquery.js'`
`import './assets/plugins/tether/dist/js/tether.js'`
`import './assets/plugins/bootstrap/dist/css/bootstrap.min.css'`
`import './assets/plugins/bootstrap/dist/js/bootstrap.min'`

I don't see any solutions anywhere.  I found similar problem in **#274**

**Comment by FezVrasta** [comment]
You should upgrade to a stable Bootstrap release. They don't use Tether anymore
