### ISSUE TITLE
production build with angular cli (uglify) results in `undefined` error

### ISSUE THREAD

**Issue by vmasek** [shipshapecode/tether#295]
In latest version (`1.4.5`) there is a strange error 
```
ERROR in main.8781be3b4db6003c3f60.js from UglifyJs
undefined
```

we tracked it to the tether, it is probably related to tree-shaking rollup/rollup/issues/1289 

## Hotfix
lower the version from `1.4.5` to `1.4.4`

----

angular-cli reference for better tracking of progress
angular/angular-cli/issues/12506

**Comment by rwwagner90** [comment]
@vmasek I believe this should be fixed now. Could you try `2.0.0-beta.2`?

**Comment by rwwagner90** [comment]
I believe this should be fixed in the latest beta, so I am going to close for now. If anyone is still experiencing issues, please let us know!
