### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by rwwagner90** [shipshapecode/tether#303]
Hello! 👋 

Awhile back, you guys transferred [Shepherd](https://github.com/shipshapecode/shepherd) to us at Ship Shape. We've since gone through several iterations with moving away from tether to popper, and now tippy, but now we are looking for ways to simplify things and ship less bytes.

I was thinking perhaps we could give using tether a try again. I am not sure of its potential downsides compared to popper these days, but it could be nice to whip tether into shape as well and potentially leverage it again.

What would you think about transferring ownership of tether as well?

**Comment by rwwagner90** [comment]
CC @FranDias I believe it was you I talked to about transferring Shepherd awhile back? I've been trying to remember who all I talked to.

**Comment by TrevorBurnham** [comment]
@rwwagner90 Howdy! Just wanted to acknowledge that we're seriously considering your proposal. We're still using Tether at HubSpot, so the idea of someone taking active stewardship is very appealing.

**Comment by rwwagner90** [comment]
Hi @TrevorBurnham, glad to hear that! The idea of taking Shepherd full circle and getting it running on a modernized Tether is really exciting to us as well 😃

**Comment by TrevorBurnham** [comment]
@rwwagner90 Let's do it! Beginning transfer now…

**Comment by TrevorBurnham** [comment]
@rwwagner90 Transfer initiated! (I had to transfer the repo to myself first—for some weird reason, GitHub will only allow self-transfers from the HubSpot org.)

Also, I'd like to add you as a maintainer to the npm package, but for some reason npm is giving me the error `Team not found` when I try to invite `rwwagner90`. Any idea what's up with that?

**Comment by rwwagner90** [comment]
@TrevorBurnham awesome! I just clicked the link and it said the transfer expired. Mind sending it once more please?

That's weird. That's definitely my username on npm https://www.npmjs.com/~rwwagner90

**Comment by TrevorBurnham** [comment]
@rwwagner90 Glad to see that went through! As far as the npm issue, apparently it's this: https://docs.npm.red/transferring-a-package-from-an-org-to-a-user-account I'll contact npm about getting the tether package removed from the HubSpot org so that non-HubSpotters like yourself can be added as an owner.

**Comment by rwwagner90** [comment]
@TrevorBurnham gotcha, that makes sense. The first bit of work will be adding tests, so we can confidently refactor things, so I think we're awhile away from an npm release, so no real rush. Just keep me posted!

**Comment by TrevorBurnham** [comment]
@rwwagner90 The npm package has been transferred over to you: https://www.npmjs.com/package/tether

**Comment by rwwagner90** [comment]
Thanks @TrevorBurnham!

**Comment by FezVrasta** [comment]
Just a heads up, Popper v2 is in its later stage of development, the size is now ~3kb and the core more robust.

It would be great to cooperate on a single project rather than splitting the efforts on several ones.

**Comment by rwwagner90** [comment]
@FezVrasta I am definitely interested to try that out! There are still a good many people using Tether though, so I would like to still try to get a v2 out.

We mainly started working on this more to use it in Shepherd, as a smaller, more simplified alternative to using Tippy + Popper, but 3kb would definitely be a nice savings.

**Comment by FezVrasta** [comment]
If you'd like to try it out we are publishing the dev releases to `@popperjs/core@next`. There's some documentation [here](https://github.com/popperjs/popper.js/tree/next/docs/src/pages)
