### ISSUE TITLE
Write tests for all examples

### ISSUE THREAD

**Issue by RobbieTheWagner** [shipshapecode/tether#313]
- [x] chosen
- [x] content-visible
- [x] ~dolls~ Doesn't seem like something we can test
- [ ] element-scroll @chuckcarpenter
- [x] enable-disable @rwwagner90 
- [x] out-of-bounds @rwwagner90 
- [x] pin @rwwagner90 
- [x] scroll @chuckcarpenter
- [x] simple @rwwagner90 
- [x] testbed @rwwagner90 
- [x] tooltip @chuckcarpenter
- [x] viewport @chuckcarpenter

**Comment by rwwagner90** [comment]
@chuckcarpenter feel free to grab some of these examples you would like to work on tests for

**Comment by chuckcarpenter** [comment]
@rwwagner90 what is `facebook`?

**Comment by rwwagner90** [comment]
@chuckcarpenter it was an example, but it used Drop heavily, so I deemed it out of scope and removed it.

**Comment by rwwagner90** [comment]
@chuckcarpenter do we still need to test `element-scroll`?

**Comment by RobbieTheWagner** [comment]
Gonna close this, test coverage is decent now.
