### ISSUE TITLE
Material-UI elements are blocked by modal

### ISSUE THREAD

**Issue by Baspa** [shipshapecode/tether#404]
I am currently using [react-shepherd](https://github.com/shipshapecode/react-shepherd) which uses Tether. The problem I am facing is the following:

![image](https://user-images.githubusercontent.com/10845460/70309398-bba4c280-180d-11ea-8382-3dcdb4f78ee4.png)

As you can see Material-UI creates another element when using their `Datepicker`, because of that I can't click on it anymore and so I am not be able to select a date properly. What would be a good way to fix this?

**Comment by rwwagner90** [comment]
This is not a tether issue. It is a Shepherd issue. Tracking here https://github.com/shipshapecode/react-shepherd/issues/152
