### ISSUE TITLE
Slow on Chrome

### ISSUE THREAD

**Issue by nharraud** [shipshapecode/tether#42]
Hi,

First thank you for your great project. It's a really good idea.

I just went to the demo page (http://tether.io/) on chrome and saw that the scrolling was really lagging a lot (it is quite unusable). The corresponding "chrome helper" process was using a lot of CPU. Here is the version I am using: 34.0.1847.131. Also I am on a Mac with Maverick 10.9.2.
On the other hand there was no problem with firefox.
It's quite strange as chrome is faster with javascript thanks to its V8 interpreter.

**Comment by TrevorBurnham** [comment]
Hmm. Is this still the case for you? Scrolling on that page isn't perfectly smooth for me, but it's not unusable either.

**Comment by rwwagner90** [comment]
I am not seeing any issues currently. If there is still a performance problem, please let us know!
