### ISSUE TITLE
Feature request: `target` keyword for `to` in constraints

### ISSUE THREAD

**Issue by kizu** [shipshapecode/tether#45]
As a follow up to my previous issue (#44) I'd like to propose a new keyword for the `to` in constraints: **`target`**. There are a lot of cases when this would make sense, for example when you'd need to have some kind of a sidebar or header that would be always visible, but only while inside its target's bounds.

Here is a brief example of how it could work: http://codepen.io/kizu/pen/qDxcA, with this keyword an example from this pen could be written just as

```
new Tether({
  element: '.element',
  target: '.content-box',
  attachment: 'bottom center',
  targetAttachment: 'bottom center',
  targetModifier: 'visible',
  constraints: [
    {
      to: 'target',
      pin: true
    },
  ]  
});
```

What do you think of it?

**Comment by NicBright** [comment]
I like this suggestion. Another use-case would be to make a <thead> always visible, as long as its table is displayed on the screen.

**Comment by tythewebguy** [comment]
+1

I've been struggling with the exact thead example NicBright describes.

**Comment by rwwagner90** [comment]
We would gladly accept a PR for this, but since this repo is largely in maintenance mode, we are unlikely to be working on active API changes. Please feel free to submit a PR if you are up to it!

**Comment by tythewebguy** [comment]
Maybe the readme file should be updated to inform people of the project's status:

"We at Ship Shape have recently taken over Tether's maintenance and hope to modernize and revitalize it. Stay tuned for updates!"

Sounds like we shouldn't stay tuned for any updates?

**Comment by rwwagner90** [comment]
@tythewebguy we made a lot of updates and modernized things, but we're not looking to rewrite the core functionality.
