### ISSUE TITLE
position using "right" property instead of "left"

### ISSUE THREAD

**Issue by yairEO** [shipshapecode/tether#57]
I really need Tether to position an element using `right` css property instead of calculate the distance using `left`, when `gpu: false`.

The reason is, that the element that is being "Tethered" can change its width and thus, it must stay on the right, no matter what it's width is, and currently this cannot be done in a smooth easy way without hacking using negative margin to push it back, which causes flickering due to browsers way of rendering.

![aaa](https://cloud.githubusercontent.com/assets/845031/3788705/b37ea880-1a72-11e4-9b54-9f67b09d5b5b.png)

As seen in the picture, the element change state from `A to B` or `B to A`, doesn't batter, it just needs to stick to the right all the time, and that "right" would be an attachment point of course.

Awesome plugin, thanks a lot.

**Comment by yairEO** [comment]
It's been almost two years since I last asked if anyone is working on it. 
shall I wait until 2025 to ask again? :)

**Comment by TrevorBurnham** [comment]
@yairEO This is certainly a good idea. Unfortunately, the positioning logic in Tether is very hairy, and I don't think improving it is anyone's top priority right now. I'd certainly welcome a PR!

**Comment by rwwagner90** [comment]
I agree with @TrevorBurnham here, so closing as won't fix, but definitely open to a PR!
