### ISSUE TITLE
Confusion about HubSpot's strategy wrt Tether based solutions

### ISSUE THREAD

**Issue by kumarharsh** [shipshapecode/tether#59]
I have a questions for the maintainers here,
You have a bunch of projects ("Tooltip", "Shepherd" and "Select") which are all based off Tether's positioning system. But still you keep bundling the whole tether into each of these library's distributable builds. WHY?

If I am to use more than of your projects, there is no simple way to include the common code (tether) once, say using RequireJS, and then just have the tooltip's and shepherd's code separately, all pulled using Bower.

Right now, I only observed that Shepherd has the [stand-alone build](https://github.com/HubSpot/shepherd/blob/624481fec8f0bc4d0d8b56cd50991197d8eac510/shepherd-amd.js) without the bundled tether code, but none of the other libraries have such organization.

Also, even with Shepherd, when I install it using bower, everything is pulled **BUT NOT** the standalone builds, which should make more sense than  :-(

Can I file this as a feature request? Have the AMD standalone builds of the libraries be distributable along with the bundled-up versions.

**Comment by dandv** [comment]
Has this been done? Looks like Kumar was going to start, but the issue is closed?

**Comment by geekjuice** [comment]
As part of the large upgrade path that occurred in the `Tether` based projects, this should be completely resolved. Each project now only include that projects source and dependencies need to be explicitly required separately. In addition, they should all be UMD.

That said, there have been requests to bring back the bundled, standalone versions, so one of the next upgrades coming (hopefully...) soon is to include a build step to include these are well.

**Comment by kumarharsh** [comment]
+1 build step is good option.
