### ISSUE TITLE
Examples not showing?

### ISSUE THREAD

**Issue by tony** [shipshapecode/tether#654]
Does anyone else have this issue?

![image](https://user-images.githubusercontent.com/26336/97121556-2a706000-16ed-11eb-9f67-fe7070e07d2a.png)

**Comment by tramax** [comment]
Same here. I'm on Chrome Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by rwwagner90** [comment]
@tony @tramax I believe things should be fixed now. We had some outdated scripts in the docs, which I removed. Please let me know if things work now!
