### ISSUE TITLE
More graceful failure in IE 8

### ISSUE THREAD

**Issue by PunkChameleon** [shipshapecode/tether#71]
Would you be open to a PR that would fail more gracefully if in IE 8? 

Right now it throws an exception (that's not entirely clear it's IE 8 related) -- it could be helpful to both have a more descriptive error, as well as not throwing an exception to stop the compiler if it is included in an IE 8 build.

**Comment by JayCarney** [comment]
+1, even if it was just a check so that if it's on IE8 it doesn't run

**Comment by zackbloom** [comment]
Do you happen to know what exception it throws?

**Comment by mnpenner** [comment]
Simply including the library breaks the entire page in IE7, probably 8 too. I'd tell you what the error is, but all IE tells me is:

> Object doesn't support this property or method

**Comment by rwwagner90** [comment]
Anyone using older IE will have to ship polyfills for things to be supported.
