### ISSUE TITLE
Tether to place elements relative to the screen?

### ISSUE THREAD

**Issue by marcusx2** [shipshapecode/tether#719]
Can I use this library simply to place elements relative to the top of the screen, bottom of the screen, top right corner, top left corner, etc?

**Comment by rwwagner90** [comment]
@marcusx2 you probably could, but for that why not use CSS?

**Comment by marcusx2** [comment]
Because I don't like CSS lol. I am looking for a library that allows me to manipulate positioning without having to touch CSS.

**Comment by rwwagner90** [comment]
@marcusx2 I don't think this is in scope. Good luck!
