### ISSUE TITLE
Location of dist folder (tether version-1.3.3)

### ISSUE THREAD

**Issue by MrFrogM** [shipshapecode/tether#978]
Hi there, I am fairly new to coding and I am following a udemy course on how to build a pipboy website ( really enjoying the process). Following along side the process , the instructor installs bootstrap and jquey. The website displays an error stating he needs tether. I do not get this error btw. He proceeds to download tether 1.3.3 (his latest version of recording) and goes to the dist folder to copy the CSS and js folders over to our project folder. I download my latest tether version (tether 2.0.0) and that dist folder is not there. 

Considering I am fairly need to web development , I was hoping someone could possibly help me out.

Thank you.

**Comment by rwwagner90** [comment]
Hi @MrFrogM if you are looking to download the files manually, you can get them from the release here https://github.com/shipshapecode/tether/releases/tag/v2.0.0
